Switch actions from enum to string
innFactory/create-react-app-material-typescript-redux pull request #20
Opened 2020-01-06 13:45 UTC by henricazottes

Having an enum caused redux-logger to display numbers instead of action's names.
Changing to strings is more user friendly.

I also scoped the Todo actions in their own file. What do you think about it ?

2020-01-07 07:33 UTC, spoeck requested changes
Your idea is very useful and I really like the concept. What do you think if we do some renamings:
```
ActionType -> Action

TodoAction -> TodoActionType

TodoActionTypes -> TodoAction

```
I think it would be more handy for using in the actions in reducers and actions

2020-01-07 13:42 UTC, henricazottes commented
I agreee with you, but to simplify imports I think we shloud also prefix `Action` with `TodoAction` but as it collides with the type name I ended up with this naming:

```
ActionType -> TodoActions 
# as it contains a list of possible actions, I think plural
# should be ok, because we need the singular for the type...

TodoAction -> TodoActionType # Ok

TodoActionTypes -> TodoAction # Ok (singular form needed here)
```
I also change `TodoActions` back to an enum type, but using string values instead of default numbers (I didn't remember I could do this this way)

Let me know what you think

2020-01-08 14:13 UTC, spoeck commented
> I agreee with you, but to simplify imports I think we shloud also prefix `Action` with `TodoAction` but as it collides with the type name I ended up with this naming:
> 
> ```
> ActionType -> TodoActions 
> # as it contains a list of possible actions, I think plural
> # should be ok, because we need the singular for the type...
> 
> TodoAction -> TodoActionType # Ok
> 
> TodoActionTypes -> TodoAction # Ok (singular form needed here)
> ```
> 
> I also change `TodoActions` back to an enum type, but using string values instead of default numbers (I didn't remember I could do this this way)
> 
> Let me know what you think

I think it's a very clear naming now :)
Thank you for your time, your PR is a real improvement for this boilerplate!

2020-01-08 14:14 UTC, spoeck approved these changes

2020-01-08 14:14 UTC, merged